In Python, error handling is primarily done using `try`, `except`, `else`, and `finally` blocks. These constructs allow you to manage exceptions (errors that occur during runtime) gracefully, enabling your program to continue running or fail in a controlled way.

In [6]:
result = 10 / 0  # This will raise a ZeroDivisionError

ZeroDivisionError: division by zero

### 1. The `try` and `except` Blocks

The `try` block contains code that might raise an exception. If an error occurs, the `except` block runs to handle it.



In [7]:
try:
    # Code that might raise an exception
    result = 10 / 0  # This will raise a ZeroDivisionError
except ZeroDivisionError:
    print("Cannot divide by zero!")


Cannot divide by zero!


In [ ]:
Data Analytics/Data Science 
multi step process 
The end goal is to extract meanigfull info 
Data collection 
Programming 
Python (Library )

Data cleaning 
Data analysis 
MAchine Learning
Deploymetn 



In [ ]:
collection of modules and functions/methods and attributes 

In [10]:
l = [1,2,3,4,5,6]

l.append(2)


In [9]:
min(l)

1

In [11]:
l

[1, 2, 3, 4, 5, 6, 2]

In [ ]:
list
dictionary
string
tuple
sets
Data type/

In [ ]:
l = [1,2,3,4,5]

### What is Numpy?

NumPy is a powerful Python library for numerical and scientific computations. It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays. NumPy is the foundation for many data science and scientific computing libraries in Python. Here are some basic concepts of NumPy:



In [ ]:
List 
Dictionary
Numpy Array (nd array)

In [12]:
l = [1,2,3,45,6]

In [14]:
import numpy as np 



In [15]:
l = np.array([1,2,3,4,5,6,8])

In [16]:
l

array([1, 2, 3, 4, 5, 6, 8])

In [20]:
type(l)

numpy.ndarray

In [17]:
l1 = [1,2,345,45]


In [19]:
type(l1)

list

In [ ]:
Dmart 

Transactional data 

Excel sheet 

In [ ]:
list 
Dictionary

In [ ]:
Numpy array 

In [21]:
l

array([1, 2, 3, 4, 5, 6, 8])

In [22]:
l1

[1, 2, 345, 45]

In [23]:
l1 + 5

TypeError: can only concatenate list (not "int") to list

In [24]:
l + 5

array([ 6,  7,  8,  9, 10, 11, 13])

In Python, arrays are implemented as lists or the more specialized `array` module, which provides a compact way to store sequences of data. However, when people often refer to arrays in Python, they might actually be talking about NumPy arrays, which are a more powerful and versatile data structure for handling numerical computations and manipulations. Let's cover both concepts:

1. **Lists** (Python's Built-in Dynamic Arrays):
   - Lists are one of the most commonly used data structures in Python.
   - Lists can hold elements of different data types.
   - They are dynamic, meaning their size can change during runtime.
   - Lists can be created using square brackets `[]` or the `list()` constructor.
   - Example:
   

In [122]:
my_list = [1, 2, 3, 4, 5]
     

In [124]:
my_list + 2

TypeError: can only concatenate list (not "int") to list

In [125]:
l = [1,2,3,45]

In [126]:
l

[1, 2, 3, 45]

2. **Array Module** (Python's Basic Array Implementation):
   - The `array` module provides a basic array implementation that is more memory-efficient than lists.
   - It requires specifying the data type of elements when creating an array.
   - Arrays are fixed in size and can't be resized.
   - Example:
   

In [120]:
from array import array
my_array = array('i', [1, 2, 3, 4, 5])  # 'i' indicates integer data type


3. **NumPy Arrays** (Powerful Numerical Arrays):
   - NumPy arrays, or `ndarrays`, are provided by the NumPy library and are widely used for numerical and scientific computations.
   - They are homogeneous (same data type) and multi-dimensional (1D, 2D, etc.).
   - NumPy arrays offer efficient element-wise operations and broadcasting.
   - They can be created using `numpy.array()` or other functions like `numpy.zeros()`, `numpy.ones()`, etc.
   - Example:
   

In [ ]:
l = []

In [21]:
import numpy as np

In [ ]:
#array

In [ ]:
array_new = np.array([1,2,3,4,5,6])

In [131]:
array_new

array([1, 2, 3, 4, 5, 6])

In [133]:
type(array_new)

numpy.ndarray

In [121]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])


When working with numerical data, using NumPy arrays is highly recommended due to their performance optimizations and a wide range of mathematical functions tailored for arrays. Here's a simple comparison:

**Using NumPy Arrays:**
```python
import numpy as np

my_array = np.array([1, 2, 3])
result = my_array * 2
print(result)  # Output: [2 4 6]
```

NumPy's ability to perform element-wise operations without explicit loops makes it a powerful tool for scientific computing and data analysis.

In [104]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])

In [105]:
my_numpy_array

array([1, 2, 3, 4, 5])

In [106]:
type(my_numpy_array)

numpy.ndarray

In [ ]:
# list Vs numpy array

In [138]:
l

[1, 2, 3, 45]

In [139]:
#list cannot do element wise operation 
l *3

[1, 2, 3, 45, 1, 2, 3, 45, 1, 2, 3, 45]

In [142]:
array_new

array([1, 2, 3, 4, 5, 6])

In [141]:
array_new * 2

array([ 2,  4,  6,  8, 10, 12])

In [107]:
import numpy as np

my_array = np.array([1, 2, 3])
result = my_array * 2
print(result)  # Output: [2 4 6]


[2 4 6]


In [108]:
l = [1, 2, 3] 

In [109]:
l*2

[1, 2, 3, 1, 2, 3]

In [ ]:
l = [[1,2,3],[1,2,3,4]]  #2D 

In [ ]:
l = [[1,2,3,4,5],
     [5,4,6,8,9],
     [4,5,8,9,10]
]

In [145]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
array_2d.ndim

2

In [146]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
l  = [1,2,3,45,6]

In [25]:
l2 =  [[1,2,3,4],[5,6,7,8,9]]

In [29]:
l2[1]

[5, 6, 7, 8, 9]

In [35]:
arr_1d = np.array([1,2,34,5])

In [33]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]])

In [36]:
arr_1d

array([ 1,  2, 34,  5])

In [34]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [37]:
arr_3d = np.arange(27).reshape(3,3,3)

In [38]:
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
videos  = lot of compressed images 

In [41]:
l3  = [[0,3,"male",22.0,1],[1,1,"female",38.0,1]]

In [42]:
np.array(l3)

array([['0', '3', 'male', '22.0', '1'],
       ['1', '1', 'female', '38.0', '1']], dtype='<U32')

In [39]:
import seaborn as sns 

In [40]:
sns.load_dataset("titanic")  #2 dimensional data 

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

# Matrix

In programming, the term "matrix" is often used to refer to a specific type of two-dimensional array. A matrix is essentially a rectangular arrangement of elements organized into rows and columns. Matrices are widely used in various fields, including mathematics, physics, computer graphics, and data analysis.

In Python, a matrix can be represented using nested lists (a list of lists) or, more commonly, using the more powerful NumPy library. Let's explore both approaches:

1. **Using Nested Lists**:
   You can represent a matrix using nested lists, where each inner list represents a row of the matrix, and the elements within each inner list correspond to the columns.

   ```python
   matrix = [
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]
   ]
   ```

2. **Using NumPy**:
   NumPy provides a dedicated `ndarray` data structure that supports multi-dimensional arrays, including matrices. Creating a matrix using NumPy is more efficient and provides numerous mathematical and numerical capabilities.

   ```python
   import numpy as np

   matrix = np.array([
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]
   ])
   ```

Matrices are particularly useful for operations involving linear algebra, transformations, and representing data that has rows and columns. Here are a few examples of operations you might perform with matrices:

- Matrix addition and subtraction.
- Matrix multiplication.
- Transposing a matrix (flipping rows and columns).
- Solving systems of linear equations using matrix operations.

In the context of machine learning and data analysis, matrices are often used to represent datasets, where each row corresponds to an observation and each column corresponds to a feature or variable.

Overall, the concept of matrices becomes relevant when you're working with data that can be organized into rows and columns and when you need to perform mathematical operations on this data structure.

In [149]:
array_2d * 10 

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
arr = np.array([1,2,3])

In [6]:
arr

array([1, 2, 3])

In [7]:


matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [8]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Read a CSV file

When you read a CSV file using the Pandas library in Python, the data is typically stored in a Pandas DataFrame. A DataFrame is a two-dimensional labeled data structure that can be thought of as a table, where each column can have a different data type. Under the hood, a DataFrame is essentially a collection of series (one-dimensional arrays), and you can indeed consider it as a form of a matrix.

Here's how it works:

1. **Reading a CSV File**:
   When you read a CSV file using Pandas' `read_csv()` function, the data is parsed and loaded into a DataFrame. Each row in the CSV file becomes a row in the DataFrame, and each column in the CSV file becomes a column in the DataFrame.

2. **DataFrame Structure**:
   A DataFrame provides a tabular structure where you can easily manipulate and analyze data. It has rows and columns, similar to a matrix.

3. **Labeling and Indexing**:
   DataFrames have row and column labels, which allow you to access and manipulate data using these labels. This is more flexible than traditional matrix indexing, where you would use numeric indices.

Here's a simple example:

```python
import pandas as pd

# Reading a CSV file into a DataFrame
data = pd.read_csv('data.csv')

# Displaying the first few rows of the DataFrame
print(data.head())

# Accessing specific values in the DataFrame
value = data.loc[0, 'column_name']
print(value)
```

In this example, the `data.csv` file is read into a DataFrame called `data`. Each row in the CSV file corresponds to a row in the DataFrame, and each column corresponds to a column. You can access specific values in the DataFrame using the `.loc[]` method, which allows you to specify both row and column labels.

So, when you work with Pandas DataFrames, you're effectively working with a data structure that has matrix-like properties, making it convenient for data analysis and manipulation tasks.

### How tabular data is represented internally

Sure! Let's say you have a Pandas DataFrame with 5 rows and 4 columns. I'll represent it as a matrix and provide the dimensions:

DataFrame:

```
   Column1  Column2  Column3  Column4
0        1        2        3        4
1        5        6        7        8
2        9       10       11       12
3       13       14       15       16
4       17       18       19       20
```

Matrix Representation:

```
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
```

In this matrix representation, each row corresponds to a row in the DataFrame, and each column corresponds to a column. The numbers in the matrix match the values in the DataFrame.

The dimensions of this matrix (and the DataFrame) are 5 rows and 4 columns. Therefore, the dimension is `(5, 4)`. In mathematical terms, this is a 5x4 matrix.

# 1D , 2D ,3D Data visually

https://stackoverflow.com/questions/61464546/what-is-the-best-way-to-store-images-in-a-numpy-array-for-building-a-cnn-with-ke

`(5, 5, 5)` represents the shape of a 3D array. Each number within the parentheses corresponds to the size of a specific dimension in the array. In this case, `(5, 5, 5)` indicates a 3D array with three dimensions, where each dimension has a size of 5.

Here's a breakdown of what each dimension represents:

- The first dimension has a size of 5. This corresponds to the number of "blocks" or "layers" in the 3D array.
- The second dimension also has a size of 5. This corresponds to the number of "rows" in each layer of the 3D array.
- The third dimension again has a size of 5. This corresponds to the number of "columns" in each row of each layer of the 3D array.

Putting it all together, a `(5, 5, 5)` 3D array has 5 blocks, each block has 5 rows, and each row has 5 columns. This results in a total of 5 x 5 x 5 = 125 elements in the 3D array.

To visualize this, you can think of the 3D array as a stack of 5 "slices," where each slice is a 5x5 matrix. The third dimension adds depth to the data structure, creating a cube-like arrangement of values.



This is just a small section of the `(5, 5, 5)` 3D array, illustrating how the dimensions play out in creating a cube of values.

### real-world examples of data with different dimensions



**1D Data**:
1. **Temperature Time Series**:
   - A sequence of temperature measurements taken at regular time intervals.
   - Each value corresponds to a single point in time.
   - Example: Daily temperature readings over a year.

2. **Stock Prices**:
   - Daily closing prices of a single stock over a period of time.
   - Each value represents the price of the stock on a specific day.
   - Example: Stock prices of a technology company over the past year.

**2D Data**:
1. **Grayscale Image**:
   - An image where each pixel's intensity is represented by a single value.
   - The 2D grid of intensity values forms the image.
   - Example: Photograph of a landscape.

2. **Tabular Data**:
   - Data organized in rows and columns, such as a spreadsheet.
   - Each row corresponds to a record, and each column corresponds to a field.
   - Example: Sales data with products, prices, and quantities sold.

**3D Data**:
1. **Medical Volumetric Data**:
   - Volumetric scans like CT or MRI with intensity values in a 3D grid.
   - Each "voxel" represents a value in 3D space.
   - Example: Brain MRI scan showing tissue intensity in 3D.

2. **Video Data with Color Channels**:
   - A video sequence with frames and color channels.
   - Each frame is a 2D image, and frames are stacked over time.
   - Example: Video footage of a moving object with red, green, and blue color channels.

**4D Data**:
1. **Functional MRI (fMRI) Data**:
   - 3D brain scans captured over time.
   - The fourth dimension represents time, showing how brain activity changes.
   - Example: Brain scan showing neural activity during a cognitive task.

2. **Video Volumetric Data**:
   - Similar to regular videos, but each frame is a 3D volume.
   - Used in applications like 4D medical imaging or dynamic simulations.
   - Example: Video showing the changing volume of a fluid flow over time.

**5D Data**:
1. **Hyperspectral Imagery**:
   - Each pixel contains information across multiple spectral bands.
   - The fifth dimension represents the spectral dimension.
   - Example: Satellite imagery capturing information across different wavelengths.

2. **Climate Model Data**:
   - Space-time data capturing climate variables across multiple layers.
   - The fifth dimension represents different climate variables.
   - Example: 5D data capturing temperature, humidity, pressure, etc., across time and space.

These examples showcase how data with different dimensions can arise in various fields and applications. Each dimension adds a layer of complexity and information to the data, making it suitable for specific types of analysis and interpretation.

### whatever data we give to machine learning or deep learning it internally gets converted into numpy nd array ??????

Yes, that's correct! In many machine learning and deep learning frameworks, including popular libraries like TensorFlow and PyTorch, data is often represented using multi-dimensional arrays. NumPy arrays are a natural choice for this purpose because they provide efficient storage, manipulation, and computation capabilities for multi-dimensional data.

When you're working with machine learning and deep learning models, your data is typically transformed into NumPy arrays before being fed into the algorithms. This applies to a wide range of data, including images, text, time series, audio, and more. Here's why NumPy arrays are commonly used:

1. **Efficient Storage**: NumPy arrays are stored in contiguous memory locations, which allows for efficient data access and operations.

2. **Mathematical Operations**: NumPy provides a rich set of mathematical and array operations that are essential for data manipulation and transformation.

3. **Interoperability**: Many machine learning libraries, including TensorFlow and PyTorch, seamlessly work with NumPy arrays. This makes it easy to integrate data processing with model training.

4. **Batch Processing**: Machine learning models often work with batches of data. NumPy arrays allow you to efficiently organize and process data in batches.

5. **Vectorization**: NumPy supports vectorized operations, which can significantly speed up computation compared to manual loops.

6. **Dimensionality**: NumPy arrays can handle data of any dimensionality, making them suitable for a wide variety of tasks.

When you're preparing data for machine learning or deep learning, you'll often perform preprocessing steps on your data, such as normalization, scaling, and feature extraction. These operations are typically done using NumPy arrays.

So, whether you're working with images, text, audio, or any other type of data, you'll likely transform it into NumPy arrays to effectively feed it into machine learning and deep learning algorithms.

### Numpy Arrays Vs Python Sequences



The key differences between NumPy arrays and Python sequences! Here's a quick summary of the points mentioned:

### **Key Differences:**

1. **Size Flexibility**:
   - **NumPy Arrays**: Fixed size at creation. Changing the size creates a new array.
   - **Python Sequences (e.g., lists)**: Can dynamically grow or shrink.

2. **Data Type**:
   - **NumPy Arrays**: All elements must be of the same data type, leading to consistent memory size.
   - **Python Sequences**: Elements can be of different data types.

3. **Performance**:
   - **NumPy Arrays**: Optimized for performance, especially for mathematical operations on large datasets.
   - **Python Sequences**: Less efficient for such operations, as they are more general-purpose.

4. **Support in Scientific Libraries**:
   - **NumPy Arrays**: Widely used in scientific and mathematical libraries. Libraries often convert Python sequences into NumPy arrays before processing.
   

Lists and NumPy arrays are both data structures in Python, but they have some significant differences, especially when it comes to handling numerical data and performing computations. Here's a comparison of key differences between lists and NumPy arrays:

1. **Memory Efficiency**:
   - Lists: Lists are less memory efficient compared to NumPy arrays because they store not only the data but also the type and other metadata for each element.
   - NumPy Arrays: NumPy arrays are more memory efficient because they store elements of the same data type in a contiguous block of memory.

2. **Data Types**:
   - Lists: Lists can contain elements of different data types (e.g., integers, strings, floats) within the same list.
   - NumPy Arrays: NumPy arrays require elements to be of the same data type, ensuring consistent and efficient computation.

3. **Computation Speed**:
   - Lists: Operations on lists are generally slower due to Python's interpreted nature and lack of optimized operations for numerical computations.
   - NumPy Arrays: NumPy provides optimized, vectorized operations that significantly speed up computations on arrays.

4. **Vectorized Operations**:
   - Lists: Python lists require explicit loops to perform element-wise operations, which can be slower and less concise.
   - NumPy Arrays: NumPy arrays support vectorized operations, allowing element-wise computations without explicit loops, leading to faster and more readable code.

5. **Broadcasting**:
   - Lists: Lists don't have built-in broadcasting capabilities, requiring explicit looping to perform operations on multiple elements.
   - NumPy Arrays: NumPy supports broadcasting, enabling operations on arrays with different shapes and dimensions.

6. **Indexing and Slicing**:
   - Lists: Indexing and slicing are common in lists, but slicing creates new copies of the list.
   - NumPy Arrays: NumPy arrays provide advanced indexing and slicing capabilities and support views (without copying) for better memory efficiency.

7. **Functionality**:
   - Lists: Lists are general-purpose and versatile, suitable for various tasks.
   - NumPy Arrays: NumPy arrays are specialized for numerical and data-centric tasks, offering a wide range of mathematical and statistical functions.

8. **Performance**:
   - Lists: Lists are slower for numerical operations due to their dynamic nature and lack of optimized operations.
   - NumPy Arrays: NumPy arrays are designed for efficient numerical computations and offer better performance for large datasets and complex operations.

9. **Interoperability**:
   - Lists: Lists are widely used and interact well with other Python libraries.
   - NumPy Arrays: NumPy arrays seamlessly integrate with scientific computing libraries like pandas, scikit-learn, and TensorFlow.

10. **Purpose**:
    - Lists: Lists are suitable for general-purpose data storage and manipulation.
    - NumPy Arrays: NumPy arrays are designed specifically for numerical data and optimized computations.

In summary, while lists are versatile and commonly used in various contexts, NumPy arrays excel in handling numerical data, offering optimized computations and memory-efficient storage. When working with numerical data or performing computations, NumPy arrays are often preferred due to their performance and convenience.

### Creating Numpy Arrays

There are several ways to create NumPy arrays in Python. Here are some of the most common methods:

1. **From Python Lists or Tuples**:
   You can create a NumPy array directly from a Python list or tuple using the `numpy.array()` function.

In [43]:
l1

[1, 2, 345, 45]

In [45]:
l + 5

array([ 6,  7,  8,  9, 10, 11, 13])

In [47]:
l5 = np.array([1,2,3,4,5,6,7])

In [49]:
l

array([1, 2, 3, 4, 5, 6, 8])

In [50]:
l5

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
l + l5

array([ 2,  4,  6,  8, 10, 12, 15])

In [51]:
l-l5

array([0, 0, 0, 0, 0, 0, 1])

In [110]:
   import numpy as np

   list_data = [1, 2, 3, 4, 5]
   array_from_list = np.array(list_data)

In [111]:
   tuple_data = (5.5, 6.6, 7.7)
   array_from_tuple = np.array(tuple_data)

In [150]:
list_data = [1, 2, 3, 4, 5]

In [151]:
a11 = np.array(list_data)

In [152]:
a11

array([1, 2, 3, 4, 5])

In [153]:
tuple_data = (5.5, 6.6, 7.7)
a22 = np.array(tuple_data)

In [154]:
a22

array([5.5, 6.6, 7.7])

2. **Using Functions to Generate Data**:
   NumPy provides functions to generate arrays with specific patterns or random data.

In [53]:
a33 = np.ones((3,4))
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [155]:
a33 = np.ones((3,4))

In [157]:
type(a33)

numpy.ndarray

In [158]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [159]:
a44 = np.zeros((2,4))

In [160]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [162]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
import numpy as np

array1 = np.array([1,2,3])



In [ ]:
   import numpy as np

   zeros_array = np.zeros((3, 3))      # Creates a 3x3 array filled with zeros

In [ ]:
   ones_array = np.ones((2, 4))        # Creates a 2x4 array filled with ones
    

In [112]:
   identity_matrix = np.eye(3)         # Creates a 3x3 identity matrix
    

In [113]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
   random_array = np.random.rand(4, 4) # Creates a 4x4 array with random values in [0, 1)

3. **Specifying Data Type**:
   You can specify the data type of the array using the `dtype` parameter.

In [163]:
l = [1,2,3,4]

In [166]:
np.array(l,dtype=np.int32 )

array([1, 2, 3, 4])

In [14]:
   import numpy as np

   int_array = np.array([1, 2, 3], dtype=np.int32)
   float_array = np.array([0.1, 0.2, 0.3], dtype=np.float64)


4. **Using arange and linspace**:
   The `np.arange()` function generates an array of values with a specified start, end, and step. The `np.linspace()` function generates an array of values spaced evenly between two points.

In [167]:
a44 = np.arange(0,12)

In [168]:
a44

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
[start:end:jump]  start includes End doesnot include 

In [56]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
np.arange(0,12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
np.arange(0,12).reshape((12,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [61]:
a22 = np.arange(0,12).reshape((6,2))

In [67]:
a33 = np.arange(64).reshape((4,4,4))

In [65]:
a33

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [15]:
   import numpy as np

   range_array = np.arange(0, 10, 2)      # Array from 0 to 10 (exclusive) with step 2
   linspace_array = np.linspace(0, 10, 5)  # Array of 5 values between 0 and 1 (inclusive)


In [68]:
linspace_array = np.linspace(0, 10, 6)
linspace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [9]:
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)



In [7]:
array_from_list

array([1, 2, 3, 4, 5])

In [ ]:
tuple_data = (5.5, 6.6, 7.7)
array_from_tuple = np.array(tuple_data)

In [8]:
zeros_array = np.zeros((3, 3))      # Creates a 3x3 array filled with zeros
ones_array = np.ones((2, 4))        # Creates a 2x4 array filled with ones
identity_matrix = np.eye(3)         # Creates a 3x3 identity matrix

random_array = np.random.rand(4, 4) # Creates a 4x4 array with random values in [0, 1)

In [9]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# np.array
import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [6]:
# 2D and 3D
b1 = np.array([[1,2,3,5],[4,5,6,8]])
print(b1)

[[1 2 3 5]
 [4 5 6 8]]


In [ ]:
[[[],[],[]]]

In [178]:
a55 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

a55

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [176]:
a55.ndim

3

In [3]:
c1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype
np.array([10,20,30,40],dtype=float)

array([10., 20., 30., 40.])

In [13]:
# np.arange
np.arange(0,11)           #same as range 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

When you use the `reshape` method in NumPy, the new shape you specify should have a total number of elements that is equal to the total number of elements in the original array. In other words, the product of the dimensions in the new shape should be equal to the product of the dimensions in the original shape.

For example, if you have a 1D array with 16 elements (as in `np.arange(16)`), you can reshape it into a 2D array with dimensions like (4, 4), (2, 8), or (8, 2) because all of these combinations have a total of 16 elements:

- 4 x 4 = 16
- 2 x 8 = 16
- 8 x 2 = 16

However, you cannot reshape it into dimensions like (3, 5) because 3 x 5 = 15, which is not equal to the original 16 elements.

So, when using `reshape`, it's important to ensure that the new shape you specify is compatible with the total number of elements in the original array.

In [11]:
# with reshape
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [184]:
np.arange(16).reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
(1,2)
(3,2,1)

In [14]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [185]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
# with reshape
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# np.ones and np.zeros
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
np.random.random((3,4))

array([[0.40373676, 0.66585025, 0.61725098, 0.75105221],
       [0.20151014, 0.10668186, 0.6335439 , 0.94065729],
       [0.49425888, 0.20547767, 0.40962531, 0.04906832]])

In [188]:
np.random.random((3,4))

array([[0.78828876, 0.1823344 , 0.20831613, 0.10702265],
       [0.67846993, 0.09070136, 0.7753702 , 0.08928025],
       [0.03588745, 0.51143957, 0.66855972, 0.73496538]])

In [16]:
# np.random
np.random.random((3,5))

array([[0.97560694, 0.5397655 , 0.36366682, 0.19670588, 0.27889291],
       [0.99845697, 0.50073169, 0.89458293, 0.09253312, 0.65705255],
       [0.67393557, 0.13848296, 0.26369241, 0.68798043, 0.67971579]])

In [10]:
# np.linspace 

np.linspace(-20,20,20,dtype=int)

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   1,   3,   5,
         7,   9,  11,  13,  15,  17,  20])

The function `np.linspace(start, stop, num)` generates an array of `num` evenly spaced values between `start` and `stop`, inclusive.

In [114]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
attributes 
methods 



In [189]:
l

[1, 2, 3, 4]

In [190]:
l.append(5)

In [191]:
l

[1, 2, 3, 4, 5]

In [ ]:
Modules 
Methods   # array,arange,reshape
attributes # 



In [74]:
l5.shape

(7,)

In [79]:
a22.dtype

dtype('int32')

In [76]:
a33

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [80]:
a22.ndim

2

In [81]:
a33.ndim

3

### Array Attributes

NumPy arrays have several attributes that provide important information about the array's properties and characteristics. These attributes can be accessed using dot notation after creating a NumPy array. Here are some common NumPy array attributes:

1. **`shape`**: Returns a tuple indicating the dimensions of the array (number of rows, number of columns, etc.).

2. **`dtype`**: Returns the data type of the elements in the array.

3. **`size`**: Returns the total number of elements in the array.

4. **`ndim`**: Returns the number of dimensions (axes) of the array.

5. **`itemsize`**: Returns the size in bytes of each element in the array.

6. **`nbytes`**: Returns the total size in bytes of the array's data.

7. **`real`**: Returns the real part of the array (for complex numbers).

8. **`imag`**: Returns the imaginary part of the array (for complex numbers).

9. **`T` or `transpose()`**: Returns the transpose of the array (rows become columns and vice versa).

10. **`flags`**: Returns an object that provides information about the memory layout and other properties of the array.

11. **`strides`**: Returns a tuple indicating the step size in bytes required to move through each dimension of the array.

12. **`base`**: Returns the base object if the array is a view on another array, or `None` if it's not a view.

Here's an example of accessing these attributes on a NumPy array:

### 1. **`ndim`** (Number of Dimensions)
- **Description**: Returns the number of dimensions (axes) of the array. A 1D array has `ndim` = 1, a 2D array has `ndim` = 2, and so on.

In [196]:
a11 = np.arange(12)
a22 = np.arange(12).reshape(3,4)
a33 = np.arange(27).reshape(3,3,3)

In [197]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [199]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [202]:
a11.ndim

1

In [203]:
a22.ndim

2

In [204]:
a33.ndim

3

In [29]:
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3])
array_1d.ndim  # Output: 1

1

In [18]:
# 2D Array
array_2d = np.array([[1, 2], [3, 4]])
array_2d.ndim  # Output: 2

2


### 2. **`shape`** (Shape of the Array)
- **Description**: Returns a tuple indicating the size of each dimension. For a 2D array, the shape will be `(rows, columns)`.

In [205]:
a11.shape

(12,)

In [206]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [207]:
a22.shape

(3, 4)

In [208]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
a33.shape

(3, 3, 3)

In [210]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
# 1D Array
array_1d.shape  # Output: (3,)

(3,)

In [20]:
# 2D Array
array_2d.shape  # Output: (2, 2)

(2, 2)

### 3. **`size`** (Total Number of Elements)
- **Description**: Returns the total number of elements in the array. It's the product of the array’s dimensions.

In [211]:
a11.size

12

In [212]:
a22.size

12

In [213]:
a22.shape

(3, 4)

In [214]:
a33.shape

(3, 3, 3)

In [21]:
# 1D Array
array_1d.size  # Output: 3

3

In [22]:
# 2D Array
array_2d.size  # Output: 4


4

### 4. **`dtype`** (Data Type of Elements)
- **Description**: Returns the data type of the elements stored in the array. It can be `int32`, `float64`, etc.

In [215]:
a11.dtype

dtype('int32')

In [216]:
a22.dtype

dtype('int32')

In [217]:
a33.dtype

dtype('int32')

In [23]:
# 1D Array
array_1d.dtype  # Output: dtype('int64') or dtype('int32') based on the system

dtype('int32')

In [24]:
# 2D Array
array_2d.dtype  # Output: dtype('int64') or dtype('int32') based on the system

dtype('int32')

### 5. **`itemsize`** (Size of Each Element in Bytes)
- **Description**: Returns the size of each element in the array in bytes.

In [218]:
a11.itemsize

4

In [25]:
# 1D Array
array_1d.itemsize  # Output: 8 (for int64, or 4 for int32 depending on your machine)

4

In [26]:
# 2D Array
array_2d.itemsize  # Output: 8 (for int64, or 4 for int32 depending on your machine)


4

In [115]:
import numpy as np 

In [119]:
a11 = np.arange(12).reshape(3,4)
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a22

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
a33

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
# ndim
a33.ndim

3

In [22]:
a11.ndim

1

In [24]:
# shape
print(a33.shape)


(2, 2, 2)


In [27]:
a11.shape

(10,)

In [6]:
# size
print(a22.size)
a22

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
a33

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
a33

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
# dtype
print(a11.dtype)
print(a22.dtype)
print(a33.dtype)



float64
int32
int32


In [83]:
a22.dtype

dtype('int32')

### Array Operations

### 1. **Addition**
- You can add two arrays element-wise.

In [219]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

In [220]:
a1

array([1, 2, 3])

In [221]:
a2

array([4, 5, 6])

In [222]:
a1+a2

array([5, 7, 9])

In [223]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [224]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
a11+a22

ValueError: operands could not be broadcast together with shapes (12,) (3,4) 

In [ ]:
import numpy as np

# Arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [63]:
# Element-wise addition
result_add = array1 + array2
result_add  # Output: array([5, 7, 9])

array([5, 7, 9])

---

### 2. **Subtraction**
- You can subtract one array from another element-wise.

In [229]:
a2 - a1

array([3, 3, 3])

In [227]:
a1

array([1, 2, 3])

In [228]:
a2

array([4, 5, 6])

In [35]:
# Element-wise subtraction
result_sub = array1 - array2
result_sub  # Output: array([-3, -3, -3])


array([-3, -3, -3])



### 3. **Multiplication**
- You can multiply two arrays element-wise.

In [230]:
a1 *a2

array([ 4, 10, 18])

In [36]:
# Element-wise multiplication
result_mul = array1 * array2
result_mul  # Output: array([4, 10, 18])


array([ 4, 10, 18])



### 4. **Division**
- You can divide one array by another element-wise.

In [231]:
a1 /a2

array([0.25, 0.4 , 0.5 ])

In [37]:
# Element-wise division
result_div = array1 / array2
result_div  # Output: array([0.25, 0.4 , 0.5])


array([0.25, 0.4 , 0.5 ])


### 5. **Scalar Operations**
- You can also perform scalar operations where a single number is applied to every element of the array.

In [84]:
a1 + 10

NameError: name 'a1' is not defined

In [233]:
a1*25

array([25, 50, 75])

In [234]:
a1 - 3

array([-2, -1,  0])

In [85]:
a22 *33

array([[  0,  33],
       [ 66,  99],
       [132, 165],
       [198, 231],
       [264, 297],
       [330, 363]])

In [237]:
a33 + 10

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [38]:
# Adding a scalar to all elements
result_scalar_add = array1 + 10
result_scalar_add  # Output: array([11, 12, 13])

array([11, 12, 13])

In [40]:
# Multiplying all elements by a scalar
result_scalar_mul = array1 * 2
result_scalar_mul  # Output: array([2, 4, 6])


array([2, 4, 6])

### 6. **Exponentiation**
- You can raise each element of an array to a specific power.

In [41]:
# Element-wise exponentiation
result_pow = array1 ** 2
result_pow  # Output: array([1, 4, 9])


array([1, 4, 9])

---

In [87]:
l1

[1, 2, 345, 45]

### 7. **Modulus**
- The modulus operation can be performed element-wise.

In [65]:
array1

array([1, 2, 3])

In [238]:
a1 %a2

array([1, 2, 3])

In [66]:
# Element-wise modulus
result_mod = array1 % 2
result_mod  # Output: array([1, 0, 1])


array([1, 0, 1], dtype=int32)

In [68]:
a = np.array([2,4,6])

In [69]:
a%2

array([0, 0, 0], dtype=int32)

### 8. **Dot Product**
- You can compute the dot product of two arrays.

In [43]:
# Dot product
result_dot = np.dot(array1, array2)
result_dot  # Output: 32 (1*4 + 2*5 + 3*6)


32

Relational operators in NumPy allow you to compare arrays element-wise, returning a boolean array as the result. Here’s how you can use them:

### 1. **Greater Than (`>`)**

In [92]:
3>= 2

True

In [91]:
3<2

False

In [93]:
True and True 

True

In [94]:
0 & 1

0

In [241]:
3>2

True

In [99]:
a22 >2

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [101]:
l

array([1, 2, 3, 4, 5, 6, 8])

In [104]:
l1[0:2]

[1, 2]

In [110]:
l[0:5]

array([1, 2, 3, 4, 5])

In [112]:
l

array([1, 2, 3, 4, 5, 6, 8])

In [111]:
l>5

array([False, False, False, False, False,  True,  True])

In [114]:
l[l>5]

array([6, 8])

In [116]:
l[4:]

array([5, 6, 8])

In [117]:
l

array([1, 2, 3, 4, 5, 6, 8])

In [118]:
l[l>2]

array([3, 4, 5, 6, 8])

In [119]:
a22 = np.arange(12).reshape((3,4))

In [120]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
a33 = np.arange(27).reshape((3,3,3))

In [122]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
&

In [128]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
(a22 >4) & (a22 < 10)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True, False, False]])

In [132]:
a22[(a22 >4) & (a22 < 10)]

array([5, 6, 7, 8, 9])

In [133]:
a11 = np.arange(12)

In [134]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
a11[0:5]

array([0, 1, 2, 3, 4])

In [142]:
a22                # rows columns 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a22[0:2  , 0:2  ]         [Start:end]    #start includes End doesnot include 

array([[0, 1],
       [4, 5]])

In [143]:
#a22[ #rows  ,#column  ]

In [144]:
a22[0]

array([0, 1, 2, 3])

In [147]:
a22[0:2,2:]

array([[2, 3],
       [6, 7]])

In [148]:
a22[1: ,1:3  ]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
#you have to be good at your operators
# you have to be good at indexing and slicing 


In [ ]:
a22[]

In [151]:
a33     # (3,3,3)   #how many 2d array ,row ,column

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
a33[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [153]:
a33[0,1]

array([3, 4, 5])

In [154]:
a33[1,1:,1:]

array([[13, 14],
       [16, 17]])

In [242]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [239]:
a11 > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
3>2

In [26]:
a21 = np.arange(12).reshape(3,4)

In [27]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a33 = np.arange(27).reshape(3,3,3)

In [29]:
a11 = np.arange(12)

In [30]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([2, 2, 4])

In [244]:
a1

array([1, 2, 3])

In [245]:
a2

array([4, 5, 6])

In [246]:
a1 < a2

array([ True,  True,  True])

In [71]:
# Element-wise greater than comparison
result_gt = array1 > array2
result_gt  # Output: array([False, False, False])

array([False, False, False])

In [32]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a11>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [33]:
a21>8

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])



### 2. **Less Than (`<`)**

In [34]:
# Element-wise less than comparison
result_lt = array1 < array2
result_lt  # Output: array([True, False, True])


array([ True,  True,  True])

In [155]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [156]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
a11>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [159]:
a11[a11>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
a22>=10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [163]:
a22[a22>=10]

array([10, 11])

In [164]:
(a22>=3)  & (a22<=8)

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [165]:
a22[(a22>=3)  & (a22<=8)]

array([3, 4, 5, 6, 7, 8])

In [166]:
mask = (a22>=3)  & (a22<=8)

In [167]:
a22[mask]

array([3, 4, 5, 6, 7, 8])

In [168]:
a22[0]

array([0, 1, 2, 3])

In [170]:
a22>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [171]:
a22[a22>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [172]:
a = a22>2

In [173]:
a22[a]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])


### 3. **Greater Than or Equal To (`>=`)**

In [37]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
3>2

True

In [41]:
a21 >= 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [249]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [250]:
a22 >= 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
# Element-wise greater than or equal to comparison
result_ge = array1 >= array2
result_ge  # Output: array([False, True, False])


array([False,  True, False])


### 4. **Less Than or Equal To (`<=`)**

In [47]:
# Element-wise less than or equal to comparison
result_le = array1 <= array2
result_le  # Output: array([True, True, True])


array([ True,  True,  True])

### 5. **Equal To (`==`)**

In [251]:
a22 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [44]:
a21 == 8

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [48]:
# Element-wise equality comparison
result_eq = array1 == array2
result_eq  # Output: array([False, True, False])


array([False,  True, False])

### 6. **Not Equal To (`!=`)**

In [46]:
l = [1,2,3,45]

In [47]:
l>2

TypeError: '>' not supported between instances of 'list' and 'int'

In [252]:
a11 != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [49]:
# Element-wise not equal comparison
result_ne = array1 != array2
result_ne  # Output: array([True, False, True])



array([ True, False,  True])


These relational operations return boolean arrays (`True` or `False`) for each element-wise comparison. They can be particularly useful for filtering data or conditional operations.

### Logical Operations on Numerical Arrays:

In [253]:
a1

array([1, 2, 3])

In [254]:
a2

array([4, 5, 6])

In [255]:
import numpy as np

# Numerical arrays
array1 = np.array([10, 20, 30, 40])

array2 = np.array([15, 20, 25, 50])

In [256]:
array1 > 15

array([False,  True,  True,  True])

In [257]:
array2 < 30

array([ True,  True,  True, False])

In [258]:
(array1 > 15) & (array2 < 30)         

array([False,  True,  True, False])

In [48]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
and &

In [49]:
(a11 >3) & (a11<10)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False])

In [56]:
# Logical AND (both conditions need to be true)
result_and = (array1 > 15) & (array2 < 30)
result_and  # Output: array([False,  True, False, False])

array([False,  True,  True, False])

In [61]:
# array1[result_and]

array([20, 30])

In [259]:
(array1 > 15)

array([False,  True,  True,  True])

In [261]:
(array2 < 30)

array([ True,  True,  True, False])

In [262]:
(array1 > 15) | (array2 < 30)

array([ True,  True,  True,  True])

In [50]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
(a21> 10) | (a21>30)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [57]:
# Logical OR (at least one condition needs to be true)
result_or = (array1 > 15) | (array2 < 30)
result_or  # Output: array([False,  True,  True,  True])

array([ True,  True,  True,  True])

In [58]:
# Logical NOT (inverts the condition)
result_not = ~(array1 > 15)
result_not  # Output: array([ True,  True, False, False])

array([ True, False, False, False])

In [176]:
True or False

True

In [ ]:
| = or 

In [ ]:
| this is a bit wise or 

In [174]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
a11+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Why use bitwise operator

In NumPy, when you use logical operators such as `&`, `|`, `~`, and `^`, they are actually **bitwise operators** rather than traditional **logical operators** like `and`, `or`, `not`, and `xor`.

Here's why NumPy uses bitwise operators for element-wise comparisons:

### Why Bitwise Operators Are Used:
1. **Element-wise Operations**:
   - NumPy arrays are optimized for element-wise operations. The operators `&`, `|`, `~`, and `^` are bitwise operators in Python, but when applied to NumPy arrays, they are interpreted to perform **element-wise logical comparisons** between elements of arrays.
   
2. **Boolean Broadcasting**:
   - Bitwise operators are overloaded in NumPy to operate on arrays and return element-wise boolean results. They work with both boolean arrays and numeric arrays where the conditions are evaluated element-wise.

3. **Performance**:
   - Using bitwise operators in this context is faster and more efficient than traditional logical operators (`and`, `or`, etc.) because they are vectorized and optimized for large-scale computations.

### Why Not Use `and`, `or`, etc.?
- **`and`, `or`, `not` in Python** are designed for single boolean values, not for arrays or lists. If you try using them with arrays, you'll get an error because they don't support element-wise comparisons.
- For array operations, Python expects logical operations to happen element-wise, which is where the bitwise operators come into play.

### Key Differences:
- **Bitwise Operators (`&`, `|`, `~`, `^`)**: Operate element-wise on arrays, but they can feel counterintuitive since they are primarily bitwise operators in other contexts.
- **Logical Functions (`np.logical_and`, `np.logical_or`)**: Clearer and specifically designed for element-wise logical operations, often preferable for readability and understanding.

In [ ]:
Any library 
collection of 
Attributes methods and functions modules 

Attribute 

In [179]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Array Methods /Functions 

Here’s a list of common and useful NumPy array functions, along with a brief description of each:

### 1. **Array Creation Functions**:
   - `np.array()`: Creates an array from a list or tuple.
   - `np.zeros()`: Creates an array filled with zeros.
   - `np.ones()`: Creates an array filled with ones.
   - `np.empty()`: Creates an uninitialized array.
   - `np.arange()`: Creates an array with evenly spaced values within a given range.
   - `np.linspace()`: Creates an array with evenly spaced values over a specified interval.
   - `np.eye()`: Creates a 2D identity matrix.
   - `np.full()`: Creates an array filled with a specified value.

### 2. **Array Attributes**:
   - `array.shape`: Returns the shape of the array.
   - `array.size`: Returns the number of elements in the array.
   - `array.ndim`: Returns the number of dimensions of the array.
   - `array.dtype`: Returns the data type of the array elements.
   - `array.itemsize`: Returns the size (in bytes) of each array element.

### 3. **Array Manipulation Functions**:
   - `np.reshape()`: Changes the shape of an array without changing its data.
   - `np.transpose()`: Reverses or permutes the dimensions of an array.
   - `np.ravel()`: Flattens the array into a 1D array.
   - `np.concatenate()`: Joins two or more arrays along an existing axis.
   - `np.vstack()`: Stacks arrays vertically (row-wise).
   - `np.hstack()`: Stacks arrays horizontally (column-wise).
   - `np.split()`: Splits an array into multiple sub-arrays.
   - `np.stack()`: Joins a sequence of arrays along a new axis.

### 4. **Mathematical Operations**:
   - `np.add()`: Adds two arrays element-wise.
   - `np.subtract()`: Subtracts one array from another element-wise.
   - `np.multiply()`: Multiplies two arrays element-wise.
   - `np.divide()`: Divides one array by another element-wise.
   - `np.power()`: Raises elements of an array to the power of another array.
   - `np.dot()`: Computes the dot product of two arrays.
   - `np.sqrt()`: Computes the square root of each element in an array.
   - `np.exp()`: Computes the exponential of all elements in the array.
   - `np.log()`: Computes the natural logarithm of each element in an array.

### 5. **Statistical Functions**:
   - `np.mean()`: Computes the arithmetic mean.
   - `np.median()`: Computes the median of the array elements.
   - `np.std()`: Computes the standard deviation.
   - `np.var()`: Computes the variance.
   - `np.min()`: Returns the minimum value of the array.
   - `np.max()`: Returns the maximum value of the array.
   - `np.sum()`: Returns the sum of array elements.
   - `np.prod()`: Returns the product of array elements.
   - `np.percentile()`: Computes the percentile of the array elements.

### 6. **Logical Functions**:
   - `np.all()`: Returns `True` if all elements of the array evaluate to `True`.
   - `np.any()`: Returns `True` if at least one element of the array evaluates to `True`.
   - `np.logical_and()`: Computes element-wise logical AND.
   - `np.logical_or()`: Computes element-wise logical OR.
   - `np.logical_not()`: Computes element-wise logical NOT.
   - `np.logical_xor()`: Computes element-wise logical XOR.

### 7. **Sorting and Searching Functions**:
   - `np.sort()`: Returns a sorted copy of an array.
   - `np.argsort()`: Returns the indices that would sort an array.
   - `np.argmax()`: Returns the indices of the maximum values along an axis.
   - `np.argmin()`: Returns the indices of the minimum values along an axis.
   - `np.searchsorted()`: Finds indices where elements should be inserted to maintain order.
   - `np.unique()`: Finds the unique elements of an array.

### 8. **Random Functions**:
   - `np.random.rand()`: Generates random numbers in the range [0, 1).
   - `np.random.randn()`: Generates random numbers from the standard normal distribution.
   - `np.random.randint()`: Generates random integers within a specified range.
   - `np.random.choice()`: Randomly selects elements from an array.
   - `np.random.seed()`: Seeds the random number generator for reproducibility.

### 9. **Array Comparison Functions**:
   - `np.equal()`: Returns a boolean array where two arrays are element-wise equal.
   - `np.not_equal()`: Returns a boolean array where two arrays are element-wise not equal.
   - `np.greater()`: Returns a boolean array where elements of the first array are greater than the second.
   - `np.less()`: Returns a boolean array where elements of the first array are less than the second.

### 10. **Linear Algebra Functions**:
   - `np.linalg.inv()`: Computes the inverse of a matrix.
   - `np.linalg.det()`: Computes the determinant of a matrix.
   - `np.linalg.eig()`: Computes the eigenvalues and eigenvectors of a matrix.
   - `np.linalg.svd()`: Computes the Singular Value Decomposition (SVD) of a matrix.
   - `np.linalg.norm()`: Computes the matrix or vector norm.

These functions are just a selection of the vast range of operations that NumPy offers. The library is designed to handle multidimensional arrays efficiently and supports a wide range of operations, making it a powerful tool for scientific computing.

## Manipulation



### 1. **`np.reshape()`**
Changes the shape of an array without altering its data.

In [53]:
a = np.arange(24)

In [54]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
a = np.arange(24).reshape(6,4)


In [56]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(array, (2, 3))
reshaped_array  # Output: array([[1, 2, 3], [4, 5, 6]])


array([[1, 2, 3],
       [4, 5, 6]])



### 2. **`np.transpose()`**
Reverses or permutes the dimensions of an array.

In [57]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
np.transpose(a21)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
array = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = np.transpose(array)
transposed_array  # Output: array([[1, 4], [2, 5], [3, 6]])


array([[1, 4],
       [2, 5],
       [3, 6]])



### 3. **`np.ravel()`**
Flattens a multi-dimensional array into a 1D array.

In [ ]:
array = np.array([[1, 2], [3, 4]])

In [59]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
np.ravel(a21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
flattened_array = np.ravel(array)
flattened_array  # Output: array([1, 2, 3, 4])

array([1, 2, 3, 4])


### 4. **`np.concatenate()`**
Joins two or more arrays along an existing axis.

In [64]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a22 = np.arange(12).reshape(3,4)

In [69]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.concatenate((a21,a22),axis = 1)   

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [75]:
np.concatenate((a21,a22),axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

np.concatenate((array1,array2),axis = 1)        #axis = 1 for column wise concatenation

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [75]:
concatenated_array = np.concatenate((array1, array2), axis=0)   #axis = 0 for row wise concatenation
concatenated_array  # Output: array([[1, 2], [3, 4], [5, 6], [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])


### 5. **`np.vstack()`**
Stacks arrays vertically (row-wise).

In [15]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [76]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.vstack((a21,a22))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
vstacked_array = np.vstack((array1, array2))
vstacked_array  # Output: array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])



### 6. **`np.hstack()`**
Stacks arrays horizontally (column-wise).

In [79]:
np.hstack((a21,a22))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [19]:
array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

In [20]:
hstacked_array = np.hstack((array1, array2))
hstacked_array  # Output: array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

### 7. **`np.split()`**
Splits an array into multiple sub-arrays.

In [78]:
array = np.array([1, 2, 3, 4, 5, 6])
split_array = np.split(array, 3)
split_array  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]

---

### 1. **`np.mean()`**  
Computes the arithmetic mean of array elements.

In [84]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
np.mean(a21)

5.5

In [97]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(array)
mean_value  # Output: 3.0


3.0

---

### 2. **`np.median()`**  
Computes the median of array elements.

In [85]:
np.median(a11)

5.5

In [86]:
a = np.arange(9)

In [87]:
np.median(a)

4.0

In [98]:
median_value = np.median(array)
median_value  # Output: 3.0


3.0

---

### 3. **`np.std()`**  
Computes the standard deviation of the array elements.

In [99]:
std_deviation = np.std(array)
std_deviation  # Output: 1.4142135623730951


1.4142135623730951

In [88]:
np.std(a11)

3.452052529534663

---

### 4. **`np.var()`**  
Computes the variance of the array elements.

In [41]:
variance_value = np.var(array)
variance_value  # Output: 2.0


2.9166666666666665

### 5. **`np.min()`**  
Returns the minimum value of the array.

In [89]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [91]:
np.min(a21)

0

In [42]:
min_value = np.min(array)
min_value  # Output: 1


1

---

### 6. **`np.max()`**  
Returns the maximum value of the array.

In [43]:
max_value = np.max(array)
max_value  # Output: 5


6

-

--

### 7. **`np.sum()`**  
Returns the sum of array elements.

In [92]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
np.sum(a21)

66

In [44]:
sum_value = np.sum(array)
sum_value  # Output: 15


21

---

### 8. **`np.prod()`**  
Returns the product of array elements.

In [94]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
np.prod(a21,axis = 0)

array([  0,  45, 120, 231])

In [96]:
np.prod(a21,axis = 1)

array([   0,  840, 7920])

In [45]:
array

array([1, 2, 3, 4, 5, 6])

In [46]:
product_value = np.prod(array,axis =0 )
product_value  # Output: 120


720

In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.prod(a,axis = 0)   #column wise


array([  0,  45, 120, 231])

In [5]:
np.prod(a,axis = 1)    #row wise

array([   0,  840, 7920])

### 1. **`np.random.rand()`**

Generates random numbers in the range [0, 1).

In [99]:
np.random.rand(50).reshape(5,10)

array([[0.70285736, 0.1973913 , 0.46010625, 0.18120232, 0.88766534,
        0.07814767, 0.70186834, 0.18190156, 0.55786153, 0.21201605],
       [0.18358126, 0.77457097, 0.50439288, 0.45043421, 0.36691502,
        0.91485913, 0.35024522, 0.87331031, 0.93546273, 0.19101471],
       [0.38528188, 0.4817405 , 0.5966701 , 0.10633858, 0.78051103,
        0.70827393, 0.27172839, 0.26345107, 0.74177171, 0.8239368 ],
       [0.4095413 , 0.57776901, 0.62869959, 0.50240337, 0.39751476,
        0.9795321 , 0.73027554, 0.60687494, 0.54805886, 0.45165364],
       [0.5789181 , 0.96653425, 0.0529752 , 0.81473592, 0.73339676,
        0.31586884, 0.91160603, 0.08210624, 0.17807556, 0.82811044]])

In [6]:
import numpy as np

# Generate 3 random numbers between 0 and 1
random_values = np.random.rand(3)
random_values  # Example Output: array([0.5488135, 0.71518937, 0.60276338])


array([0.7326409 , 0.57706473, 0.28887097])

### 2. **`np.random.randn()`**
Generates random numbers from the standard normal distribution (mean = 0, std dev = 1).

In [7]:
# Generate 3 random numbers from a standard normal distribution
random_normal = np.random.randn(3)
random_normal  # Example Output: array([-0.97727788, 0.95008842, -0.15135721])


array([-0.76852279, -0.33701604, -0.81916249])

### 3. **`np.random.randint()`**
Generates random integers within a specified range.

In [103]:
np.random.randint(1,10,5)

array([9, 3, 3, 1, 7])

In [ ]:
# Generate 3 random integers between 1 and 10
random_integers = np.random.randint(1, 10, 3)
random_integers  # Example Output: array([3, 7, 2])


### 4. **`np.random.choice()`**
Randomly selects elements from an array.

In [104]:
a = np.arange(12)

In [105]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
np.random.choice(a,5)

array([ 2,  1,  2, 10,  1])

In [8]:
array = np.array([10, 20, 30, 40, 50])

# Randomly select 3 elements from the array
random_choice = np.random.choice(array, 3)
random_choice  # Example Output: array([30, 20, 50])


array([50, 20, 30])

### Indexing and Slicing

### **Indexing and Slicing in NumPy**

Indexing and slicing in NumPy are similar to how they are done with Python lists but provide additional flexibility and power for multidimensional arrays.


### **1. Indexing in NumPy Arrays**

**Indexing** allows you to access individual elements or groups of elements within the array. You can use square brackets `[]` to index into arrays.

In [114]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
a11[0:3]

array([0, 1, 2])

#### Example: 1D Array Indexing

In [ ]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

In [ ]:
# Access the first element
first_element = array[0]  # Output: 10

In [20]:
# Access the last element
last_element = array[-1]  # Output: 50

#### Example: 2D Array Indexing

In [120]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
a21[1,0]

4

In [122]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
a21[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [128]:
a21[0:2,2:]

array([[2, 3],
       [6, 7]])

In [129]:
a21[1,1]

5

In [ ]:
a21[]

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# Access the element at row 1, column 2
element = array_2d[1, 2]  # Output: 6

In [ ]:
# Access the first row
first_row = array_2d[0]  # Output: array([1, 2, 3])

In [ ]:
# Access the first column
first_column = array_2d[:, 0]  # Output: array([1, 4, 7])

---

### **2. Slicing in NumPy Arrays**

**Slicing** allows you to access a subset of elements from an array. You can specify the start, stop, and step for each axis of the array.

The syntax is:
```python
array[start:stop:step]
```

#### Example: 1D Array Slicing

In [21]:
array = np.array([10, 20, 30, 40, 50])

# Slice from index 1 to 4
slice_1 = array[1:4]  # Output: array([20, 30, 40])

In [22]:
# Slice with a step of 2
slice_2 = array[::2]  # Output: array([10, 30, 50])

In [23]:
# Slice from index 2 to the end
slice_3 = array[2:]  # Output: array([30, 40, 50])

#### Example: 2D Array Slicing

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the first two rows and the first two columns
slice_2d = array_2d[:2, :2]  # Output: array([[1, 2], [4, 5]])

In [ ]:
# Slice the last two rows
last_two_rows = array_2d[1:, :]  # Output: array([[4, 5, 6], [7, 8, 9]])

In [ ]:
# Slice every other element from the first row
slice_row = array_2d[0, ::2]  # Output: array([1, 3])

### **Boolean Indexing in NumPy**

**Boolean indexing** in NumPy is a powerful technique to select elements of an array based on conditions. This allows for filtering arrays based on whether the elements meet a specific condition, such as being greater than a certain value, being equal to another element, or any other comparison.

Instead of using indices to access elements, you use a **boolean array** (an array of `True` and `False` values) where each boolean value corresponds to an element in the original array. If the boolean value is `True`, the corresponding element is included in the output; if it's `False`, it's excluded.

### **How Boolean Indexing Works**

1. **Condition-based selection**: You create a boolean mask (an array of `True` and `False`) by applying a condition on the array.
2. **Apply the boolean mask**: Use this boolean mask to filter out the elements that satisfy the condition.

---

### **Steps for Boolean Indexing**

1. **Create a NumPy array**.
2. **Apply a condition** to generate a boolean array.
3. **Use the boolean array** to index the original array and extract the desired elements.

### **Examples of Boolean Indexing**

#### Example 1: Simple Boolean Indexing

In [135]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [138]:
a11>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [136]:
mask = a11>3

In [137]:
a11[mask]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [139]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [141]:
a11[a11>5]

array([ 6,  7,  8,  9, 10, 11])

In [142]:
a11[a11>=5]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

In [24]:
# Create a boolean mask for elements greater than 25
mask = array > 25  # Output: array([False, False, True, True, True])

# Use the mask to filter the original array
filtered_array = array[mask]  # Output: array([30, 40, 50])

In this example:
- The condition `array > 25` creates a boolean mask where each element of the array is checked if it's greater than 25.
- The resulting boolean array (`mask`) is `[False, False, True, True, True]`.
- Applying this mask on `array` returns only the elements where the mask is `True`, i.e., `[30, 40, 50]`.

#### Example 2: Boolean Indexing with Multiple Conditions

You can combine multiple conditions using logical operators (`&`, `|`, `~`, etc.) for more complex filtering.

In [25]:
array = np.array([10, 20, 30, 40, 50])

# Apply multiple conditions: elements greater than 15 and less than 45
mask = (array > 15) & (array < 45)

# Filter the original array using the combined condition
filtered_array = array[mask]  # Output: array([20, 30, 40])


In [143]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
mask = (a21>=5) & (a21<=9)

In [146]:
a21[mask]

array([5, 6, 7, 8, 9])

In this example:
- The condition `(array > 15) & (array < 45)` creates a boolean mask that checks if each element is both greater than 15 and less than 45.
- The mask is `[False, True, True, True, False]`, and applying it to the array returns `[20, 30, 40]`.

#### Example 3: Using `np.where()` for Conditional Filtering

In [150]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
np.where(a11>6)

(array([ 7,  8,  9, 10, 11], dtype=int64),)

In [152]:
a55 = np.array([5,87,99,66,88,55,44])

In [154]:
np.where(a55>66)

(array([1, 2, 4], dtype=int64),)

You can use `np.where()` to return the indices where a condition is `True` or to return specific values based on the condition.

In [ ]:
array = np.array([10, 20, 30, 40, 50])

In [ ]:
# Use np.where() to find indices where elements are greater than 30
indices = np.where(array > 30)  # Output: (array([3, 4]),)

In [26]:
# Extract the elements that satisfy the condition using np.where()
filtered_array = array[indices]  # Output: array([40, 50])

In [167]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [168]:
np.where(array > 30)

(array([3, 4], dtype=int64),)


#### Example 4: Boolean Indexing with Strings

Boolean indexing also works with arrays of other types, like strings.

In [44]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve',"Ajau"])

# Create a boolean mask for names that start with the letter 'A'
mask = np.char.startswith(names, 'A')

# Use the mask to filter the original array
names[mask]  # Output: array(['Alice'], dtype='<U7')


array(['Alice', 'Ajau'], dtype='<U7')

In [169]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve',"Ajau"])

In [170]:
names

array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Ajau'], dtype='<U7')

In [171]:
np.char.startswith(names,"A")

array([ True, False, False, False, False,  True])

In [172]:
names[np.char.startswith(names,"A")]

array(['Alice', 'Ajau'], dtype='<U7')

In [173]:
a = "hello world"

In [174]:
a.startswith("a")

False

#### Example 5: Replacing Values with Boolean Indexing

You can also **modify or replace values** in an array based on a condition.

In [28]:
array = np.array([10, 20, 30, 40, 50])

# Replace all elements greater than 30 with the value 99
array[array > 30] = 99  # Output: array([10, 20, 30, 99, 99])


In [177]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [179]:
a11> 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True])

In [181]:
a11[a11>4] = 8

In [182]:
a11

array([0, 1, 2, 3, 4, 8, 8, 8, 8, 8, 8, 8])

Here, all elements in `array` that are greater than 30 are replaced with the value `99`.

### **Common Use Cases for Boolean Indexing**

1. **Filtering data**: Select elements that meet a condition (e.g., find all temperatures above a threshold).
2. **Replacing values**: Modify elements based on a condition (e.g., replace negative values with zero).
3. **Masking**: Create masks that can be used for further analysis (e.g., mask certain parts of an image in computer vision).
4. **Finding indices**: Locate the indices where a condition is met (e.g., find the positions of all even numbers).

---

### **Key Points:**
- Boolean indexing creates a mask (a boolean array) to filter elements in an array.
- Multiple conditions can be combined using logical operators (`&`, `|`, etc.).
- You can use boolean indexing for both numeric and non-numeric arrays.
- It’s a very powerful tool for data manipulation, especially when working with large datasets.

Boolean indexing is highly efficient and a central part of performing array operations in NumPy.

In [206]:
l = [1,2,3]

In [207]:
l[0]

1

In [208]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [209]:
a11[a11>5]

array([ 6,  7,  8,  9, 10, 11])

### **Fancy Indexing in NumPy**

**Fancy indexing** in NumPy allows you to access multiple elements from an array at once by passing an array (or list) of indices. Unlike basic slicing, where we can only specify a continuous range of elements, fancy indexing enables selecting non-contiguous or arbitrary elements from an array. This can be done with 1D, 2D, or even multi-dimensional arrays.


### **Key Points about Fancy Indexing:**
- Fancy indexing allows the use of integer arrays (or lists) to index into another array.
- It creates copies of the data, unlike basic slicing, which provides views (i.e., the data in the original array remains unchanged).
- Fancy indexing can be used with both one-dimensional and multi-dimensional arrays.
- You can use fancy indexing with multiple index arrays (e.g., rows and columns for 2D arrays).

---

### **1. Fancy Indexing in 1D Arrays**

When you pass an array (or list) of indices, NumPy selects the corresponding elements from the original array.

#### Example: Fancy Indexing with a 1D Array

In [45]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

# Select elements at index 1, 3, and 4
fancy_indexed = array[[1, 3, 4]]  # Output: array([20, 40, 50])

In [189]:
a55

array([ 5, 87, 99, 66, 88, 55, 44])

In [191]:
a55[[1,3,6]]

array([87, 66, 44])

In [46]:
# Using negative indices
fancy_indexed_neg = array[[-1, -3]]  # Output: array([50, 30])

In this example:
- The list `[1, 3, 4]` specifies the indices of the elements we want to select from `array`.
- Fancy indexing returns the elements `[20, 40, 50]`, corresponding to indices 1, 3, and 4.

### **2. Fancy Indexing in 2D Arrays**

With 2D arrays, fancy indexing allows you to specify the indices for rows and columns. You can select individual elements, entire rows, or columns using lists or arrays of indices.

#### Example: Fancy Indexing with a 2D Array

In [194]:
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

In [197]:
array_2d[1,0:]

array([40, 50, 60])

In [198]:
array_2d[[0, 1, 2],[1, 0, 2]]

array([20, 40, 90])

In [47]:
# Select specific elements from the 2D array
array_2d[[0, 1, 2], [1, 0, 2]]  # Output: array([20, 40, 90])

array([20, 40, 90])

In this example:
- The lists `[0, 1, 2]` and `[1, 0, 2]` specify the row and column indices, respectively.
- Fancy indexing selects the elements `array_2d[0, 1]`, `array_2d[1, 0]`, and `array_2d[2, 2]`, which are `[20, 40, 90]`.

#### Example: Selecting Rows or Columns using Fancy Indexing

You can also use fancy indexing to select entire rows or columns.

In [36]:
# Select the 0th and 2nd rows
rows = array_2d[[0, 2]]  # Output: array([[10, 20, 30], [70, 80, 90]])

# Select the 1st and 2nd columns (fancy indexing on columns)
columns = array_2d[:, [1, 2]]  # Output: array([[20, 30], [50, 60], [80, 90]])


In this example:
- `array_2d[[0, 2]]` selects the rows at index 0 and 2.
- `array_2d[:, [1, 2]]` selects the columns at index 1 and 2 from all rows.

---

### **3. Fancy Indexing with Repetition**

You can use the same index multiple times in the list or array of indices to repeat certain elements in the output.

#### Example: Repeating Elements with Fancy Indexing

In [202]:
array = np.array([100, 200, 300, 400, 500])

In [203]:
array

array([100, 200, 300, 400, 500])

In [205]:
array[[0,4,0,4]]

array([100, 500, 100, 500])

In [51]:
# Repeat the first and last elements
array[[0, 4, 0, 4]]  # Output: array([100, 500, 100, 500])

array([100, 500, 100, 500])

In this example:
- The indices `[0, 4, 0, 4]` are used to repeat the first and last elements of the array.
- The output is `[100, 500, 100, 500]`.

---

### **4. Fancy Indexing with Boolean Arrays**

Fancy indexing can also be combined with **boolean indexing**, where a boolean array is used to specify which elements to include in the result.

#### Example: Boolean Mask with Fancy Indexing

In [52]:
array = np.array([5, 10, 15, 20, 25, 30])

In [53]:
# Create a boolean mask for elements greater than 15
mask = array > 15  # Output: array([False, False, False, True, True, True])

In [54]:
# Use the boolean mask for fancy indexing
fancy_indexed = array[mask]  # Output: array([20, 25, 30])

In this example:
- The condition `array > 15` generates a boolean array, which acts as a mask.
- The fancy indexing returns the elements where the mask is `True`, i.e., `[20, 25, 30]`.

---

### **5. Fancy Indexing vs Basic Slicing**

- **Basic slicing**: You can only select a continuous range of elements.
  - Example: `array[1:4]` selects elements from index 1 to 3.
- **Fancy indexing**: You can select arbitrary elements by providing arrays/lists of indices.
  - Example: `array[[0, 3, 4]]` selects elements at indices 0, 3, and 4.

#### Comparison Example:

In [39]:
array = np.array([10, 20, 30, 40, 50])

# Basic slicing: continuous range of elements
slice_result = array[1:4]  # Output: array([20, 30, 40])

# Fancy indexing: arbitrary indices
fancy_indexed = array[[0, 2, 4]]  # Output: array([10, 30, 50])


In this example:
- Basic slicing gives a continuous range `[20, 30, 40]`.
- Fancy indexing allows selecting non-contiguous elements `[10, 30, 50]`.

---

### **Key Takeaways**
- Fancy indexing is a way to access multiple elements or rows/columns simultaneously using arrays or lists of indices.
- It is more flexible than basic slicing since it allows the selection of non-contiguous elements.
- Fancy indexing creates a new copy of the data, unlike slicing, which returns a view.
- It works with multi-dimensional arrays, enabling complex and arbitrary selections.

Fancy indexing is useful in advanced data manipulation and selection tasks in NumPy.

### Iterating

In [210]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [211]:
for i in a11:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [212]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a21 = [ [0,1,2,3],[4,5,6,7],[8,9,10,11]]

In [213]:
for i in a21:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [214]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [215]:
for i in a33:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [24]:
a11

for i in a11:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [25]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
for i in a22:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [37]:
a33

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
for i in a33:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [216]:
for i in np.nditer(a33):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Stacking

`np.hstack()` is a function provided by the NumPy library in Python, and it is used to horizontally stack (or concatenate) two or more arrays along their horizontal axis (axis 1). This means it combines the arrays side by side, extending the number of columns while keeping the number of rows unchanged or aligned.

Here's the basic syntax of `np.hstack()`:

```python
result = np.hstack((array1, array2, ...))
```



- `array1`, `array2`, etc.: These are the arrays you want to horizontally stack. You can provide multiple arrays as arguments within a tuple.

- `result`: This is the resulting array obtained after horizontally stacking the input arrays.

Here's an example to illustrate how `np.hstack()` works:

```python
import numpy as np

array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

result = np.hstack((array1, array2))

print(result)
```

Output:
```
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])
```

In this example, `np.hstack()` combines `array1` and `array2` horizontally, creating a new array with all the columns from both arrays. The number of rows remains the same (2 rows), and the number of columns increases because they are stacked side by side.

`np.hstack()` is particularly useful when you want to combine data from multiple arrays with the same number of rows but different attributes (columns).

`np.vstack()` is a function provided by the NumPy library in Python, and it is used to vertically stack (or concatenate) two or more arrays along their vertical axis (axis 0). This means it combines the arrays on top of each other, extending the number of rows while keeping the number of columns unchanged or aligned.

Here's the basic syntax of `np.vstack()`:

```python
result = np.vstack((array1, array2, ...))
```

- `array1`, `array2`, etc.: These are the arrays you want to vertically stack. You can provide multiple arrays as arguments within a tuple.

- `result`: This is the resulting array obtained after vertically stacking the input arrays.

Here's an example to illustrate how `np.vstack()` works:

```python
import numpy as np

array1 = np.array([1, 2])
array2 = np.array([3, 4])

result = np.vstack((array1, array2))

print(result)
```

Output:
```
array([[1, 2],
       [3, 4]])
```

In this example, `np.vstack()` combines `array1` and `array2` vertically, creating a new array with all the rows from both arrays. The number of columns remains the same (2 columns), and the number of rows increases because they are stacked on top of each other.

`np.vstack()` is particularly useful when you want to combine data from multiple arrays with the same number of columns but different observations (rows).

In [217]:
# horizontal stacking
a44 = np.arange(12).reshape(3,4)
a55 = np.arange(12,24).reshape(3,4)


In [218]:
a44

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [219]:
a55

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [220]:
np.hstack((a44,a55))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [32]:
np.hstack((a44,a55))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [33]:
# Vertical stacking
np.vstack((a44,a55))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [221]:
np.vstack((a44,a55))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [222]:
a44

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [223]:
a55

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

`np.hsplit()` and `np.vsplit()` are functions provided by the NumPy library in Python, and they are used to split arrays into smaller sub-arrays along either the horizontal (columns) or vertical (rows) axis, respectively.

1. **`np.hsplit()` (Horizontal Split):**
   - `np.hsplit(array, num_splits)`: Splits an array horizontally (along columns) into `num_splits` sub-arrays of approximately equal column-wise size.
   - The `array` is split into sub-arrays by dividing it into sections along the horizontal axis (axis 1).
   - The result is a list of sub-arrays.

   Example:
   ```python
   import numpy as np

   array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

   splits = np.hsplit(array, 2)

   print(splits)
   ```
   Output:
   ```
   [array([[1, 2],
           [5, 6]]), array([[3, 4],
                              [7, 8]])]
   ```

2. **`np.vsplit()` (Vertical Split):**
   - `np.vsplit(array, num_splits)`: Splits an array vertically (along rows) into `num_splits` sub-arrays of approximately equal row-wise size.
   - The `array` is split into sub-arrays by dividing it into sections along the vertical axis (axis 0).
   - The result is a list of sub-arrays.

   Example:
   ```python
   import numpy as np

   array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

   splits = np.vsplit(array, 3)

   print(splits)
   ```
   Output:
   ```
   [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
   ```

Both `np.hsplit()` and `np.vsplit()` are useful when you want to divide a larger array into smaller, more manageable pieces along specific axes. The resulting sub-arrays are typically stored in a list.

In [225]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

splits = np.hsplit(array, 2)

print(splits)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [226]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [228]:
np.hsplit(array,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [55]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

splits = np.vsplit(array, 3)

print(splits)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [21]:
#unequal split not possible 
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

splits = np.hsplit(array, 3)

print(splits)


ValueError: array split does not result in an equal division

In [231]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [232]:
splits = np.vsplit(array, 3)

print(splits)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [39]:
#unequal split not possible 
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

splits = np.vsplit(array, 2)

print(splits)


ValueError: array split does not result in an equal division

# Array Mutability

In NumPy, arrays are mutable, which means you can modify their elements after they are created. This mutability is one of the key features of NumPy arrays and is in contrast to some other data structures in Python, like tuples, which are immutable.

Here's how you can update elements in a NumPy array:

1. **Direct Element Assignment:**
   You can directly assign a new value to a specific element of a NumPy array using indexing. For example:

In [5]:
   import numpy as np

   arr = np.array([1, 2, 3, 4, 5])
   arr[2] = 99  # Update the third element to 99


2. **Slicing and Assignment:**
   You can use slicing to update multiple elements at once. For example:

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 0  # Update elements at indices 1, 2, and 3 to 0


3. **Boolean Mask and Assignment:**
   You can use a Boolean mask to conditionally update elements based on a condition. For example:

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
arr[mask] = 99  # Update elements greater than 2 to 99


In [233]:
arr

array([ 1,  2, 99, 99, 99])

In [234]:
arr> 80

array([False, False,  True,  True,  True])

In [236]:
arr[arr>80] =0

In [237]:
arr

array([1, 2, 0, 0, 0])